services:

  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - user-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-db:/data
    ports:
      - "6379:6379"
    networks:
      - internal      

volumes:
  user-db:
    driver: local
    name: user-db
  redis-db:
    driver: local
    name: redis-db

networks:
  internal:
    driver: bridge
    name: internal    